// Builds src/data/dict.ts from the word-list package + a curated common-word set.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const SRC_DICT = '/tmp/package/words.txt';

const SUBSTR = [
  'fuck', 'shit', 'cunt', 'nigg', 'rape', 'whore', 'bitch', 'tranny', 'retard',
  'kike', 'spic', 'chink', 'dyke', 'pedo', 'molest', 'nazi', 'hitler', 'wetback',
  'towelhead', 'beaner', 'gook', 'slut', 'fag', 'piss', 'cock', 'titt', 'boob',
  'penis', 'vagina', 'dildo', 'orgas', 'semen', 'sperm', 'clit', 'rectum',
  'bastard', 'bollock', 'wank', 'twat', 'negro', 'jap', 'abo', 'paki', 'raghead',
];
const EXACT = new Set([
  'sex', 'anal', 'ass', 'asses', 'asshole', 'cum', 'arse', 'arsey', 'tit', 'tits',
  'gay', 'gays', 'damn', 'damned', 'hell', 'hells', 'crap', 'craps', 'crapped',
  'pee', 'peed', 'poop', 'pooped', 'turd', 'turds', 'fart', 'farts', 'farted',
  'boob', 'boobs', 'booby', 'butt', 'butts', 'nut', 'nuts', 'dick', 'dicks',
  'wang', 'weenie', 'wiener', 'pimp', 'pimps', 'ho', 'hos', 'johns', 'dong',
]);

const blocked = (w) => EXACT.has(w) || SUBSTR.some((s) => w.includes(s));

const raw = fs.readFileSync(SRC_DICT, 'utf8').split('\n');
const dict = [];
for (const line of raw) {
  const w = line.trim().toLowerCase();
  if (w.length < 3 || w.length > 9) continue;
  if (!/^[a-z]+$/.test(w)) continue;
  if (blocked(w)) continue;
  dict.push(w);
}
dict.sort();
const dictSet = new Set(dict);

// Frequency tiers: the smaller the source list, the more familiar the word.
const level = (n) => JSON.parse(fs.readFileSync(`/tmp/wl/package/english-words-${n}.json`, 'utf8'));
const primer = new Set(level('10').map((w) => w.toLowerCase()));
const wider = new Set([
  ...level('20'), ...level('35'), ...level('50'), ...level('55'), ...level('60'),
].map((w) => w.toLowerCase()));

const common = dict.filter((w) => primer.has(w) || wider.has(w));
// Most familiar first, then shortest first so seeds land on punchy words.
const primerBank = dict
  .filter((w) => primer.has(w) && w.length >= 3 && w.length <= 6)
  .sort((a, b) => a.length - b.length || a.localeCompare(b));

console.log('dict', dict.length, 'common', common.length, 'primer', primerBank.length);

/**
 * Front-coding: consecutive words share prefixes, so each entry stores the
 * shared-prefix length (as a control character) plus the new suffix. Decodes
 * back to the exact list and gzips far better than the raw text.
 */
const encode = (list) => {
  let prev = '';
  const parts = [];
  for (const w of list) {
    let i = 0;
    while (i < prev.length && i < w.length && prev[i] === w[i]) i++;
    parts.push(String.fromCharCode(i) + w.slice(i));
    prev = w;
  }
  return parts.join('\n');
};

const emit = (name, list, doc) =>
  `// Generated by tools/build-dict.mjs - do not edit by hand.\n` +
  `// ${doc}\n` +
  `// Front-coded: prefix length + suffix per entry.\n` +
  `export const ${name} = ${JSON.stringify(encode(list))};\n`;

fs.mkdirSync(path.join(ROOT, 'src/data'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'src/data/dict.ts'), emit('DICT_RAW', dict, 'Every playable word, A-Z, sorted.'));
fs.writeFileSync(path.join(ROOT, 'src/data/common.ts'), emit('COMMON_RAW', common, 'Familiar words, ordered by obscurity then length.'));
fs.writeFileSync(path.join(ROOT, 'src/data/primer.ts'), emit('PRIMER_RAW', primerBank, 'Very familiar 3-6 letter words, for rack seeding.'));
console.log('written');
